### ISSUE TITLE
t-sne init error

### ISSUE THREAD

**Issue by jameshadfield** [blab/pathogen-embed#5]
Running `pathogen-embed ... t-sne` resulted in the error `TSNE.__init__() got an unexpected keyword argument 'square_distances'`. The same command but with `umap` or `mds` worked as expected. Happy to provide input data if that helps. 

pathogen-embed version: 1.1.1 (via PyPi)
Python 3.10.13
scikit-learn Version: 1.4.0

**Comment by huddlej** [comment]
Thanks for reporting this, @jameshadfield! It looks like [that parameter was added in 0.24 and then removed in scikit-learn v1.3](https://scikit-learn.org/stable/whats_new/v0.24.html#sklearn-manifold). The default behavior since 1.3 should be what we want, but [we use 0.24.2 in our paper](https://github.com/blab/cartography/blob/4ae0f38b92cbf59b1f3495409a2908f79cb33e3e/cartography.yml#L17) and should probably pin to that for now.
